### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Failed to load questions_usage_by_activity 21

### ISSUE THREAD

**Issue by sparry0407** [richardjonesnz/moodle_mod_simplelesson#10]
I have a simple two page lesson, each with a different single short answer question. When I click check, sometimes it checks the answer, but sometimes it fails as follows:
```
Coding error detected, it must be fixed by a programmer: Failed to load questions_usage_by_activity 27

More information about this error
Debug info:
Error code: codingerror
Stack trace:

    line 478 of /question/engine/datalib.php: coding_exception thrown
    line 84 of /question/engine/lib.php: call to question_engine_data_mapper->load_questions_usage_by_activity()
    line 75 of /mod/simplelesson/showpage.php: call to question_engine::load_questions_usage_by_activity()
```

**Comment by richardjonesnz** [comment]
I haven't managed to reproduce but will take a look.  Which version are you using please (see version.php)?

**Comment by sparry0407** [comment]
First the Moodle version info:

defined('MOODLE_INTERNAL') || die();

$version  = 2019111805.15;              // 20191118      = branching date YYYYMMDD - do not modify!
                                       //         RR    = release increments - 00 in DEV branches.
                                       //           .XX = incremental changes.
$release  = '3.8.5+ (Build: 20201030)'; // Human-friendly version name
$branch   = '38';                       // This version's branch.
$maturity = MATURITY_STABLE;             // This version's maturity level.


and now the plugin itself:

/**
* Plug-in version and dependencies description.
* @package    qtype_vplquestion
* @copyright  Astor Bizard, 2019
* @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
*/

defined('MOODLE_INTERNAL') || die();

$plugin->component = 'qtype_vplquestion';
$plugin->version   = 2020102900;
$plugin->requires  = 2018051700; // Moodle 3.5.
$plugin->maturity  = MATURITY_STABLE;
$plugin->release = '1.3.4';

$plugin->dependencies = array('mod_vpl' => 2017112412); // VPL 3.3.



________________________________

**Comment by richardjonesnz** [comment]
I can't guarantee that the Simple Lesson plugin will work with all question types, especially third-party ones.  If I have time I will install the required mod and question type and see if I can fix this bug.

**Comment by sparry0407** [comment]
Many apologies Richard; I got you and another plugin author mixed up - I sent you the version data for the wrong plugin. Here is what I should have sent:

defined('MOODLE_INTERNAL') || die();

$plugin->component = 'mod_simplelesson';
$plugin->version = 2020030200;
$plugin->release = 'v1.29.1'; // Fixed navigation issues.
$plugin->requires = 2017111301; // Designed for Moodle 3.5.
$plugin->maturity = MATURITY_BETA;
$plugin->cron = 0;
$plugin->dependencies = array();

The question type that shows this behaviour is just the standard short answer.
I have been able to work round the bug as follows:

  1.  I had a non-question page as my first page.
  2.  I patched showpage.php to allow the Next and Prev buttons to always appear on non-question pages (I need the disable incomplete). Diff to follow.

It seems the saving does not always 'stick' - perhaps a transaction issue?
________________________________

**Comment by sparry0407** [comment]
The version of the plugin I was using is the last official released plugin. Having looked at master I can see that the code has change a fair bit, so I am trying again using the latest. I have also sent a PR for the "no nav buttons" issue.
________________________________

**Comment by sparry0407** [comment]
Having checked against the latest code, I cannot reproduce it; it appears to be fixed. Please can we have a new release? (but see my PR for issue #11). Thanks and sorry for the hassle.
