### ISSUE TITLE
Cannot navigate on non-question pages with "Do not allow incomplete attempts" enabled

### ISSUE THREAD

**Issue by sparry0407** [richardjonesnz/moodle_mod_simplelesson#11]
Steps to reproduce:

- Create a lesson with three pages.
- Make the first a non-question page.
- Make pages two and three question pages allocating short answer questions.
- Ensure "Do not allow incomplete attempts" is ticked in the settings
- Save the lesson
- Start an attempt

What should happen:

- First page should appear with home and next

What actually happens:

- First page appears with no buttons.

**Comment by richardjonesnz** [comment]
Is this still open?

**Comment by sparry0407** [comment]
have not checked thoroughly but i am happy to close this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
