### ISSUE TITLE
Provide link to questions from the manage questions page.

### ISSUE THREAD

**Issue by sparry0407** [richardjonesnz/moodle_mod_simplelesson#13]
Please could you add the means to navigate from the lesson "manage questions" page directly to the question in the question bank - it can be very tedious manually navigating to a question in the question bank.

**Comment by richardjonesnz** [comment]
Probably.  I'm taking a little break for the next couple of weeks but will keep it on todo list.

**Comment by sparry0407** [comment]
Thanks Richard, it is very appreciated. You have provided the community with a real productivity enhancing tool. The simple lesson module I think would make a worthy inclusion in the core Moodle product. It seems a no brainer to me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by richardjonesnz** [comment]
Hi Stephen, I've added a link to the question bank.  I think it's more useful the the preview page because (IDKW) you cannot edit a question on the preview page nor is there a link to do so (which is a pity).  The new link is on the Manage Questions page.

Close if happy.

**Comment by sparry0407** [comment]
Thanks, I will give this a try later...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by richardjonesnz** [comment]
Closed it anyway...
