### ISSUE TITLE
Broken page layout in Clean theme

### ISSUE THREAD

**Issue by mudrd8mz** [richardjonesnz/moodle_mod_simplelesson#2]
When attempting a lesson on a site with the Clean theme, it seems the page is somehow broken:

![image](https://user-images.githubusercontent.com/85831/44233569-80a7f700-a1a4-11e8-8b6d-91f4b6d4980c.png)

**Comment by richardjonesnz** [comment]
This: https://moodle.org/mod/forum/discuss.php?d=373899 is a spanner in the works eh?  Should I worry about Clean?  It also breaks my nice Mustache templates (used to improve the UI) which are using Bootstrap 4.

**Comment by richardjonesnz** [comment]
OK now, found stray divs in the renderer.  Also have improved the UI look and feel.

**Comment by mudrd8mz** [comment]
> Should I worry about Clean?

(1) Clean is still a standard theme on latest Moodle version (2) Problems like may suggest some underlying problems, such as this stray divs which should be fixed anyway. Thanks for fixing this.
