### ISSUE TITLE
Can't add questions

### ISSUE THREAD

**Issue by DR-Bi** [richardjonesnz/moodle_mod_simplelesson#7]
Hiya,

I can't add questions to the Simple lesson, nor to its content pages. It's just a loop of 'Add questions' and 'Save changes' buttons. Neither has any other clear, relevant instructions as far as I can tell.

Otherwise, I love it massively. So much faster and easier to work with than Lessons.

Thanks

**Comment by richardjonesnz** [comment]
Hello Dr

Have you set a category for the questions in the activity settings and then clicked add questions?  You should then see the questions from the category with checkboxes beside them.  Check the ones you want to use within the lesson.  If necessary, you can go back to Simple lesson settings and pick more categories to add questions from.

Once the questions are selected, you can add them to a page via the add questions interface.

Documentation (manual, video demo) can be found here: https://open-learning.co.nz/course/view.php?id=17.  You can log on as a guest to view them.

Hope this helps and thanks.

Please close the issue when/if it is resolved for you.

**Comment by DR-Bi** [comment]
Ah, right.

Thanks, the problem was indeed not having selected question categories in the simple lesson settings. (I need to sort my course's question categories to make this easier, anyway.)
Thanks very much! I had missed the 'log in as guest' part, but that's super helpful.
