### ISSUE TITLE
Possible capitalization error

### ISSUE THREAD

**Issue by drachels** [richardjonesnz/moodle_mod_simplelesson#8]
Hi Richard, 
Was doing some research trying to learn about mustache templates by seeing what your had done. I happened to notice what might be a capitalization error in one of your strings. In the simplelesson.php language file of version 1.28, line 94, the column heading string, sequence, should be capitalized to match the other headings.
I really like the ease of use of your plugin, especially the capability to use the regular question bank.

**Comment by richardjonesnz** [comment]
Hi Al,
Good to hear from you.  I really need to go back and look at the plugin again but I have too much work on at the moment and I should be retired by now.  Thanks for that, I think you are right about the capital letter.

Thanks also for your kind words, I think it could be extended and improved as I see it's still using html_writer quite a bit and I'm now a huge fan of Mustache.

**Comment by drachels** [comment]
I retired four and half years ago and now work even more...but just on fun things.
