### ISSUE TITLE
Link to Simple lessons in an Activities block is broken

### ISSUE THREAD

**Issue by drachels** [richardjonesnz/moodle_mod_simplelesson#9]
Using v1.28 of Simple lesson, if I click on it's link in a course Activities block, I get a debug message saying, 
Exception - Class 'course_module_instance_list_viewed' not found
More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 35 of /mod/simplelesson/index.php: Error thrown

When I look at the index.php file, in line 26 I see that, \**course_module_instance_list_viewed**, is missing from the line of code for, **use**.
Code as found in index.php line 26:
use \mod_simplelesson\event;
Changing the line of code to this, then the index.php page shows up as expected:
use \mod_simplelesson\event\course_module_instance_list_viewed;

Just want to say, Thanks!, again for this plugin. The more I use it, the more I like it as it is so simple to set up a lesson when compared to the normal lesson plugin.  And, since I am a novice when it come to programming in PHP, I am using your code to learn how to move all my localib.php classes to the classes folders and also how to start using mustache files, as my MooTyper plugin so far is totally broken in Moodle master branch which is the upcoming Moodle 3.8 code.

**Comment by richardjonesnz** [comment]
Thank you Al, I will implement that fix shortly.  I released it as a BETA so always glad to get feedback.  

You can also see the different code stages I use for my workshops/courses in moodle-block_superframe and moodle-mod_collaborate.  They both use Mustache extensively - which I really like.

I believe there is much talk in the community about re-writing the Lesson so I'm not sure how far to take Simple Lesson.  It was a learning journey as much as anything else.
